# Proper Nugget Smelting by ThizThizzyDizzy
# Version 1.1.0

# Use these multipliers to control how many nuggets each material will return.
chainmail-multiplier: 0.5
iron-multiplier: 1
gold-multiplier: 1